server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.112.64.113:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

